version: '{branch}-{build}'

clone_depth: 10

environment:
  PACMAN_OPTIONS: "--needed --noconfirm --noprogressbar --overwrite \\*"
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: MINGW32

build_script:
  - del C:\Windows\system32\libssl-*.dll C:\Windows\system32\libcrypto-*.dll
  - C:\msys64\usr\bin\pacman -Syuu %PACMAN_OPTIONS%
  - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/buildtools/appveyor.sh"

artifacts:
  - path: build\inkscape*.7z
  - path: build\inkscape*.exe
  - path: build\inkscape*.msi

cache:
  - '%APPVEYOR_BUILD_FOLDER%\build\ccache'

test: off
