image: ubuntu:16.04

before_script:
  - apt-get update -yqq 
  # Tools
  - apt-get install -y -qq cmake intltool pkg-config python-dev libtool
  # Libraries
  - apt-get install -y -qq libart-2.0-dev libaspell-dev libboost-dev libcdr-dev libgc-dev libgdl-3-dev libglib2.0-dev libgnomevfs2-dev libgsl-dev libgtk-3-dev libgtkmm-3.0-dev libgtkspell-dev liblcms2-dev libmagick++-dev libpango1.0-dev libpng12-dev libpoppler-glib-dev libpoppler-private-dev libpopt-dev libpotrace-dev librevenge-dev libsigc++-2.0-dev libvisio-dev libwpg-dev libxml-parser-perl libxml2-dev libxslt1-dev libyaml-dev python-lxml zlib1g-dev
  # Testing Tools
  - apt-get install -y -qq google-mock libgtest-dev
  # Generate Makefiles

inkscape:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd ..
    - tar vfcz inkscape.tgz build/
  artifacts:
    paths:
      - inkscape.tgz

test:
  stage: test
  script:
    - tar xvfz inkscape.tgz
    - cd build
    - make test
