before_script:
  - apt-get update -qq && apt-get install -y -qq cmake intltool libart-2.0-dev libaspell-dev libboost-dev libcdr-dev libgc-dev libgdl-3-dev libglib2.0-dev libgnomevfs2-dev libgsl0-dev libgtk-3-dev libgtkmm-3.0-dev libgtkspell-dev liblcms2-dev libmagick++-dev libpango1.0-dev libpng12-dev libpoppler-glib-dev libpoppler-private-dev libpopt-dev libpotrace-dev librevenge-dev libsigc++-2.0-dev libtool libvisio-dev libwpg-dev libxml-parser-perl libxml2-dev libxslt1-dev pkg-config python-dev python-lxml zlib1g-dev
  - cmake .

inkscape:
  script:
    - make
  stage: build
