image: tedg/inkscape-ci-docker

before_script:
  # CCache Config
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache

cache:
  paths:
    - ccache/

# Building inkscape
inkscape:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Debug
    - make -j3
    - cd ..
  artifacts:
    expire_in: 1 year
    paths:
      - build/

# This job is a static analysis build by clang.
# It takes MORE THAN 3 HOURS, and depending on worker sometimes 4 hours.
# Make sure the timeout of the build is big enough
clang:
  stage: build
  only: 
    - schedules
  script:
    - apt-get install -y clang-3.8 clang
    - mkdir -p clang-build
    - cd clang-build
    - scan-build cmake .. -DCMAKE_BUILD_TYPE=Debug
    - VERBOSE=1 scan-build -o ../scan make -j2
  artifacts:
    paths:
      - scan/

test:
  stage: test
  script:
    - cd build
    - make test

# uploads the clang scan to user.gitlab.io/inkscape/
pages:
  stage: deploy
  when: manual
  dependencies:
    - clang
  script:
    - if test -e scan; then cp -r scan/* public; fi
  artifacts:
    paths:
      - public
  only:
    - master
