name: inkscape
version: 0.91+devel
summary: Vector Graphics Editor
description: |
 An Open Source vector graphics editor, with capabilities similar to
 Illustrator, CorelDraw, or Xara X, using the W3C standard Scalable Vector
 Graphics (SVG) file format.

 Inkscape supports many advanced SVG features (markers, clones, alpha blending,
 etc.) and great care is taken in designing a streamlined interface.
 It is very easy to edit nodes, perform complex path operations, trace
 bitmaps and much more.
 
 We also aim to maintain a thriving user and developer community by using
 open, community-oriented development.
confinement: devmode # use "strict" to enforce system access only via declared interfaces

parts:
  inkscape:
    plugin: cmake
    source: .
    configflags: ['-DENABLE_BINRELOC=ON']
  snapcraft-wrapper:
    plugin: copy
    files:
      snapcraft.sh: snapcraft.sh
  gtklaunch:
    plugin: make
    source: https://github.com/dplanella/gtkconf.git

apps:
  inkscape:
    command: snapcraft.sh gtk-launch inkscape
  viewer:
    command: snapcraft.sh gtk-launch inkview
